bilibili:
  copyright: 1
  default_tid: 21
  default_tags:
  - VTuber
  - hololive
  - 虚拟主播
  auto_cover: true
  cover_source: thumbnail
  season_id: null
  templates:
    title: '【${channel_name}|${brand}】${translated_title} | #${playlist_index}'
    description: '摘要:${tldr}


      完整简介：${translated_desc}


      ━━━━━━━━━━━━━━━━━━━━━━


      📺 原视频: ${source_url}

      📺 原始标题: ${original_title}

      📅 原发布日期: ${original_date}

      ⏱️ 时长: ${duration}

      📺 原频道: ${channel_name}

      🔗 频道链接: ${channel_url}


      ━━━━━━━━━━━━━━━━━━━━━━

      🤖 关于本翻译


      本视频由 AI 全自动翻译生成，全流程无人工参与，作者不对其中任何言论的内容或翻译准确性负责。

      🔧 ASR: Whisper ${whisper_model} | 断句: ${split_model} | 优化: ${optimize_model} | 翻译: ${translate_model}

      成本约 0.1~0.5 元/小时视频，用爱发电。如收到任何支持，将用于填补翻译成本的token费用。

      翻译质量：基本通顺，除专有名词外与人工翻译区别不大。多人对话、歌唱场景识别效果有限。

      项目初衷："有个翻译总比没有好"

      欢迎基于视频质量、翻译方式等提出意见，也诚邀有兴趣的开发人员和字幕制作者交流（群：1047066927）


      ━━━━━━━━━━━━━━━━━━━━━━

      📂 项目相关


      如对该翻译框架有兴趣，请查看：${project_url}


      ${project_description}


      该项目开源主要是提供了“机翻的整个流程”，并且人工可以任意编辑其中的环节。供有能力进行日语翻译者加工，以及技术人员和爱好者基于AI进行翻译。


      如有翻译建议或技术交流，欢迎访问项目仓库（点点star吧.jpg）。


      ━━━━━━━━━━━━━━━━━━━━━━

      ⚠️ 版权声明


      如相关版权方提出依据中国现行法律的侵权意见，

      本人将在收到消息核实后尽快删除相关视频，对造成的不便深表歉意。

      本视频仅供学习 LLM 相关技术以及日语交流使用。

      '
    custom_vars:
      brand: 全熟
      project_description: 开源项目 VAT (Video Auto Translator) - 自动翻译视频
      project_url: https://github.com/112292454/Video-Auto-Translator
