bilibili:
  copyright: 1
  default_tid: 21
  default_tags:
  - VTuber
  - hololive
  - 虚拟主播
  auto_cover: true
  cover_source: thumbnail
  season_id: null
  templates:
    title: '【${channel_name}|${brand}】${translated_title} | #${playlist_index}'
    description: '摘要:${tldr}


      完整简介：${translated_desc}


      ━━━━━━━━━━━━━━━━━━━━━━


      📺 原视频: ${source_url}

      📺 原始标题: ${original_title}

      📅 原发布日期: ${original_date}

      ⏱️ 时长: ${duration}

      📺 原频道: ${channel_name}

      🔗 频道链接: ${channel_url}


      ━━━━━━━━━━━━━━━━━━━━━━

      🤖 关于本翻译


      本视频由 AI 全自动翻译生成，全流程无人工参与，作者不对其中任何言论的内容或翻译准确性负责。 
      
      🔧 ASR: Whisper ${whisper_model} | 断句: ${split_model} | 优化: ${optimize_model} | 翻译: ${translate_model}

      成本约 0.1~0.5 元/小时视频，取决于模型。用爱发电，如收到任何支持，将用于填补翻译成本的token费用。


      欢迎基于视频质量、翻译方式等提出意见（建议通过github或群内。评论会看但可能不及时）
      

      也欢迎对视频内容感兴趣的朋友们、开发者与字幕制作者加群交流（群号：1047066927）


      ━━━━━━━━━━━━━━━━━━━━━━

      📂 项目相关


      如对该视频的翻译方法有兴趣，请查看：${project_url}


      该项目开源提供了基于大语言模型机翻的全流程，可以本地部署，供无日语基础的用户自行翻译喜欢的视频。也可以人工编辑其中的任何环节，供有能力进行校对的用户进一步加工。


      任何翻译建议、技术交流或使用疑惑，都欢迎访问项目仓库（宣传一下吧，给孩子点点star吧.jpg）。


      ━━━━━━━━━━━━━━━━━━━━━━

      ⚠️ 版权声明

      本视频遵照 https://hololivepro.com/terms/ 的条款进行翻译和发布。


      本视频仅供学习使用。在上述官方条款基础上，遵循 CC BY 4.0 协议。

      '
    custom_vars:
      brand: 全熟
      project_description: 开源项目 VAT (Video Auto Translator) - 自动翻译视频
      project_url: https://github.com/ZeyuanGuo/Video-Auto-Translator
